{% set package = "molecule-signature" %}
{% set version = "2.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ package|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/molecule-signature/archive/refs/tags/{{ version }}.tar.gz
  sha256: d2f9d796885266c283fc69f8472523752f74566f9066e378f46ea72384c6a920

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - networkx
    - numpy
    - pandas
    - python
    - rdkit
    - scipy
    - sympy

test:
  source_files:
    - tests
  imports:
    - molsig
  requires:
    - python {{ python_min }}
    - pytest
  commands:
    - python -m pytest

about:
  home: https://github.com/brsynth/molecule-signature
  summary: Signature-based enumeration of molecules from morgan fingerprints
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tduigou
