{% set package = "molecule-signature" %}
{% set version = "2.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ package|lower }}
  version: {{ version }}

source:
  url: https://github.com/brsynth/molecule-signature/archive/refs/tags/{{ version }}.tar.gz
  sha256: 896ae6b71d6b8f2a8f2a6942ce3f68eec5160ad541b6b49691d2363d1f75e251

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - networkx
    - numpy
    - pandas
    - python
    - rdkit
    - scipy
    - sympy

test:
  source_files:
    - tests
  imports:
    - molsig
  requires:
    - python {{ python_min }}
    - pytest
  commands:
    - python -m pytest

about:
  home: https://github.com/brsynth/molecule-signature
  summary: Signature-based enumeration of molecules from morgan fingerprints
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tduigou
